import Head from "next/head";
import { PageWrapper } from "../components/PageWrapper";
import { RadioGroup } from "../components/RadioGroup";
import { ToggleSwitch } from "../components/ToggleSwitch";

const rows = [
  { day: "Monday", enabled: true },
  { day: "Tuesday" },
  { day: "Wednesday" },
  { day: "Thursday" },
  { day: "Friday" },
  { day: "Saturday" },
  { day: "Sunday" },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <PageWrapper>
        <h1 className="text-2xl font-bold mb-4">Availability</h1>
        <div className="bg-white shadow overflow-hidden sm:rounded-lg">
          <div className="px-4 py-5 sm:px-6">
            <p className="mt-1 max-w-2xl text-md text-gray-400 font-semibold">
              What are your operating hours?{" "}
            </p>
          </div>
          {rows.map(({ day }) => (
            <Row title={day} key={day} />
          ))}
        </div>
      </PageWrapper>
    </div>
  );
}

function Row({ title }) {
  const notificationMethods = [
    { id: "default", title: "6:00 am - 12:00 am", enabled: true },
    { id: "custom", title: "Customize hours", enabled: true },
  ];

  return (
    <div className="border-gray-200 px-4 py-5 sm:p-0">
      <dl className="sm:divide-y sm:divide-gray-200">
        <div className="py-4 sm:py-5 sm:grid sm:grid-cols-6 sm:gap-4 sm:px-6">
          <dt className="text-md font-bold text-black">{title}</dt>
          <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-1">
            <ToggleSwitch enabled={true} onChange={() => {}} />
          </dd>
          <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-4">
            <RadioGroup
              notificationMethods={notificationMethods}
              name={title + "notification-method"}
            />
          </dd>
        </div>
      </dl>
    </div>
  );
}
